# Generated by Django 4.2.6 on 2023-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='coffee_name',
            field=models.CharField(max_length=40),
        ),
    ]
